name: PHP Test Coverage

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar PHP e Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, pdo, xml, dom
          coverage: xdebug

      - name: Instalar dependências
        run: composer install --prefer-dist --no-progress --no-scripts

      - name: Rodar testes com cobertura
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Salvar cobertura como artefato
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-html
          path: coverage-html/
